name: Beginner CI implementation


on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
        matrix:
          node-version: [ 16, 18, 20]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: cache
        uses: actions/checkout@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ HashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: setup node
        uses: actions/checkout@v4
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

